package com.codex.chat.core.connector

import android.content.Context
import android.content.SharedPreferences

/**
 * Gestor de Conectores IA (Google Flow y futuras extensiones).
 * Permite seleccionar el conector activo, tipo de medio (imagen o video) y orquestar llamadas.
 */
class MediaConnectorManager(
    private val context: Context? = null,
    private val client: MediaConnectorClient = MediaConnectorClient()
) {
    private val prefs: SharedPreferences? = context?.getSharedPreferences("connector_prefs", Context.MODE_PRIVATE)

    var isConnectorActive: Boolean = false
        private set

    var activeConnectorType: MediaConnectorType = MediaConnectorType.IMAGE
        private set

    var activeProvider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW
        private set

    var config: MediaConnectorConfig = loadConfig()
        private set

    fun activate(type: MediaConnectorType, provider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW) {
        isConnectorActive = true
        activeConnectorType = type
        activeProvider = provider
        if (config.provider != provider) {
            updateConfig(config.copy(provider = provider))
        }
    }

    fun deactivate() {
        isConnectorActive = false
    }

    fun clearActiveConnector() {
        deactivate()
    }

    fun setActiveConnector(provider: ConnectorProvider, type: MediaConnectorType) {
        activate(type, provider)
    }

    // Public property getters generated by Kotlin automatically

    fun getConfig(provider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW): MediaConnectorConfig {
        return if (config.provider == provider) config else config.copy(provider = provider)
    }

    fun updateConfig(newConfig: MediaConnectorConfig) {
        config = newConfig
        activeProvider = newConfig.provider
        saveConfig(newConfig)
    }

    private val videoTriggerPrefixes = listOf(
        "🎬 [Google Flow - Veo 3.1]:", "🎬 [Google Flow]:", "🎬 [Veo 3.1]:", "🎬 [Veo 2]:", "🎬 [Video]:", "🎬",
        "/veo", "/video", "generar video:", "generar video", "crear video de", "crear video", "creame un video de",
        "créame un video de", "hazme un video de", "haz un video de", "genera un video de", "crea un video de",
        "crea un video:", "genera un video:", "hazme un video:", "haz un video:", "crear un video:",
        "anima esta imagen", "animar esta imagen", "anima la imagen", "animar imagen", "anima esta foto",
        "animar foto", "anima la foto", "animar esta foto"
    )

    private val imageTriggerPrefixes = listOf(
        "🎨 [Google Flow - Imagen 3.1]:", "🎨 [Google Flow]:", "🎨 [Imagen 3.1]:", "🎨 [Imagen 3]:", "🎨 [Imagen]:", "🎨",
        "/flow", "/googleflow", "/imagen", "/image", "/draw", "generar imagen:", "generar imagen", "crear imagen de",
        "crear imagen", "creame una imagen de", "créame una imagen de", "hazme una imagen de", "haz una imagen de",
        "genera una imagen de", "crea una imagen de", "crea una imagen:", "genera una imagen:", "hazme una imagen:",
        "dibuja una imagen de", "dibuja:", "dibuja", "dibújame una imagen de", "dibújame", "dibujame",
        "edita esta imagen:", "edita esta imagen", "editar imagen:", "editar imagen", "modifica esta imagen:",
        "modifica esta imagen", "retoca esta imagen:", "retoca esta imagen"
    )

    fun isConnectorTrigger(text: String): Boolean {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) return false

        if (isConnectorActive) return true

        val lower = trimmed.lowercase()
        return videoTriggerPrefixes.any { lower.startsWith(it) } ||
               imageTriggerPrefixes.any { lower.startsWith(it) }
    }

    fun detectTrigger(text: String): MediaConnectorType? {
        if (!isConnectorTrigger(text)) return null
        return resolveConnectorType(text)
    }

    fun resolveConnectorType(text: String): MediaConnectorType {
        val lower = text.trim().lowercase()
        if (videoTriggerPrefixes.any { lower.startsWith(it) }) {
            return MediaConnectorType.VIDEO
        }
        if (imageTriggerPrefixes.any { lower.startsWith(it) }) {
            return MediaConnectorType.IMAGE
        }
        return activeConnectorType
    }

    fun extractPrompt(text: String): String {
        var clean = text.trim()
        val allPrefixes = (videoTriggerPrefixes + imageTriggerPrefixes).sortedByDescending { it.length }

        for (prefix in allPrefixes) {
            if (clean.startsWith(prefix, ignoreCase = true)) {
                clean = clean.substring(prefix.length).trim().trimStart(':', '-', ' ')
                break
            }
        }
        return if (clean.isNotBlank()) clean else text.trim()
    }

    fun executeGeneration(
        prompt: String,
        type: MediaConnectorType? = null,
        attachedImage: String? = null
    ): MediaGenerationResult {
        val targetType = type ?: activeConnectorType
        val cleanPrompt = extractPrompt(prompt)

        return when (targetType) {
            MediaConnectorType.IMAGE -> client.generateImage(cleanPrompt, config, attachedImage)
            MediaConnectorType.VIDEO -> client.generateVideo(cleanPrompt, config, attachedImage)
        }
    }

    fun getClient(): MediaConnectorClient = client

    private fun loadConfig(): MediaConnectorConfig {
        if (prefs == null) return MediaConnectorConfig()
        val providerId = prefs.getString("connector_provider_id", ConnectorProvider.GOOGLE_FLOW.id)
        val provider = ConnectorProvider.fromId(providerId)

        return MediaConnectorConfig(
            provider = provider,
            baseUrl = prefs.getString("connector_base_url", "http://127.0.0.1:8317/v1") ?: "http://127.0.0.1:8317/v1",
            apiKey = prefs.getString("connector_api_key", "proxy-pool") ?: "proxy-pool",
            imageModel = prefs.getString("connector_image_model", "imagen-3.1") ?: "imagen-3.1",
            videoModel = prefs.getString("connector_video_model", "veo-3.1") ?: "veo-3.1",
            imageSize = prefs.getString("connector_image_size", "1024x1024") ?: "1024x1024",
            videoAspectRatio = prefs.getString("connector_video_aspect_ratio", "16:9") ?: "16:9",
            videoDuration = prefs.getInt("connector_video_duration", 5),
            responseFormat = prefs.getString("connector_response_format", "b64_json") ?: "b64_json"
        )
    }

    var cachedCredits: FlowCreditsResponse = loadCachedCredits()
        private set

    private fun loadCachedCredits(): FlowCreditsResponse {
        val rem = prefs?.getFloat("cached_credits_remaining", 0f)?.toDouble() ?: 0.0
        val tot = prefs?.getFloat("cached_credits_total", 0f)?.toDouble() ?: 0.0
        val acc = prefs?.getString("cached_credits_account", "") ?: ""
        return FlowCreditsResponse(
            status = if (tot > 0) "ok" else "initial",
            account = acc,
            creditsRemaining = rem,
            creditsTotal = tot,
            isConnected = tot > 0
        )
    }

    fun updateCredits(credits: FlowCreditsResponse) {
        cachedCredits = credits
        prefs?.edit()?.apply {
            putFloat("cached_credits_remaining", credits.creditsRemaining.toFloat())
            putFloat("cached_credits_total", credits.creditsTotal.toFloat())
            putString("cached_credits_account", credits.account)
            apply()
        }
    }

    fun updateCreditsAfterGeneration(cost: Double, remaining: Double, total: Double, account: String? = null) {
        val newRem = if (remaining > 0.0) remaining else maxOf(0.0, cachedCredits.creditsRemaining - cost)
        val newTot = if (total > 0.0) total else cachedCredits.creditsTotal
        val newAcc = account ?: cachedCredits.account
        updateCredits(cachedCredits.copy(
            creditsRemaining = newRem,
            creditsTotal = newTot,
            account = newAcc,
            isConnected = true
        ))
    }

    fun updateCreditsAfterGeneration(result: MediaGenerationResult) {
        val cost = result.creditsCost ?: 0.0
        val rem = result.creditsRemaining ?: 0.0
        val tot = result.creditsTotal ?: 0.0
        updateCreditsAfterGeneration(cost, rem, tot, result.accountEmail)
    }

    fun saveConfig(c: MediaConnectorConfig) {
        config = c
        activeProvider = c.provider
        prefs?.edit()?.apply {
            putString("connector_provider_id", c.provider.id)
            putString("connector_base_url", c.baseUrl)
            putString("connector_api_key", c.apiKey)
            putString("connector_image_model", c.imageModel)
            putString("connector_video_model", c.videoModel)
            putString("connector_image_size", c.imageSize)
            putString("connector_video_aspect_ratio", c.videoAspectRatio)
            putInt("connector_video_duration", c.videoDuration)
            putString("connector_response_format", c.responseFormat)
            apply()
        }
    }
}
