package com.codex.chat.core.connector

import android.content.Context
import android.content.SharedPreferences

/**
 * Gestor de Conectores IA (Google Flow y futuras extensiones).
 * Permite seleccionar el conector activo, tipo de medio (imagen o video) y orquestar llamadas.
 */
class MediaConnectorManager(
    private val context: Context? = null,
    private val client: MediaConnectorClient = MediaConnectorClient()
) {
    private val prefs: SharedPreferences? = context?.getSharedPreferences("connector_prefs", Context.MODE_PRIVATE)

    var isConnectorActive: Boolean = false
        private set

    var activeConnectorType: MediaConnectorType = MediaConnectorType.IMAGE
        private set

    var activeProvider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW
        private set

    var config: MediaConnectorConfig = loadConfig()
        private set

    fun activate(type: MediaConnectorType, provider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW) {
        isConnectorActive = true
        activeConnectorType = type
        activeProvider = provider
        if (config.provider != provider) {
            updateConfig(config.copy(provider = provider))
        }
    }

    fun deactivate() {
        isConnectorActive = false
    }

    fun clearActiveConnector() {
        deactivate()
    }

    fun setActiveConnector(provider: ConnectorProvider, type: MediaConnectorType) {
        activate(type, provider)
    }

    // Public property getters generated by Kotlin automatically

    fun getConfig(provider: ConnectorProvider = ConnectorProvider.GOOGLE_FLOW): MediaConnectorConfig {
        return if (config.provider == provider) config else config.copy(provider = provider)
    }

    fun updateConfig(newConfig: MediaConnectorConfig) {
        config = newConfig
        activeProvider = newConfig.provider
        saveConfig(newConfig)
    }

    fun isConnectorTrigger(text: String): Boolean {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) return false

        if (isConnectorActive) return true

        val lower = trimmed.lowercase()
        return lower.startsWith("🎨") ||
                lower.startsWith("🎬") ||
                lower.startsWith("/flow") ||
                lower.startsWith("/googleflow") ||
                lower.startsWith("/imagen") ||
                lower.startsWith("/image") ||
                lower.startsWith("/veo") ||
                lower.startsWith("/video") ||
                lower.startsWith("generar imagen:") ||
                lower.startsWith("generar video:")
    }

    fun detectTrigger(text: String): MediaConnectorType? {
        if (!isConnectorTrigger(text)) return null
        return resolveConnectorType(text)
    }

    fun resolveConnectorType(text: String): MediaConnectorType {
        val lower = text.trim().lowercase()
        return when {
            lower.startsWith("🎬") || lower.startsWith("/veo") || lower.startsWith("/video") || lower.startsWith("generar video:") -> {
                MediaConnectorType.VIDEO
            }
            lower.startsWith("🎨") || lower.startsWith("/imagen") || lower.startsWith("/image") || lower.startsWith("generar imagen:") -> {
                MediaConnectorType.IMAGE
            }
            else -> activeConnectorType
        }
    }

    fun extractPrompt(text: String): String {
        var clean = text.trim()
        val prefixes = listOf(
            "🎨 [Google Flow - Imagen 3.1]:", "🎨 [Google Flow]:", "🎨 [Imagen 3.1]:", "🎨 [Imagen 3]:", "🎨 [Imagen]:", "🎨",
            "🎬 [Google Flow - Veo 3.1]:", "🎬 [Google Flow]:", "🎬 [Veo 3.1]:", "🎬 [Veo 2]:", "🎬 [Video]:", "🎬",
            "/flow", "/googleflow", "/imagen", "/image", "/veo", "/video",
            "generar imagen:", "generar video:"
        )

        for (prefix in prefixes) {
            if (clean.startsWith(prefix, ignoreCase = true)) {
                clean = clean.substring(prefix.length).trim()
                break
            }
        }
        return clean
    }

    fun executeGeneration(prompt: String, type: MediaConnectorType? = null): MediaGenerationResult {
        val targetType = type ?: activeConnectorType
        val cleanPrompt = extractPrompt(prompt)

        return when (targetType) {
            MediaConnectorType.IMAGE -> client.generateImage(cleanPrompt, config)
            MediaConnectorType.VIDEO -> client.generateVideo(cleanPrompt, config)
        }
    }

    fun getClient(): MediaConnectorClient = client

    private fun loadConfig(): MediaConnectorConfig {
        if (prefs == null) return MediaConnectorConfig()
        val providerId = prefs.getString("connector_provider_id", ConnectorProvider.GOOGLE_FLOW.id)
        val provider = ConnectorProvider.fromId(providerId)

        return MediaConnectorConfig(
            provider = provider,
            baseUrl = prefs.getString("connector_base_url", "http://127.0.0.1:8317/v1") ?: "http://127.0.0.1:8317/v1",
            apiKey = prefs.getString("connector_api_key", "proxy-pool") ?: "proxy-pool",
            imageModel = prefs.getString("connector_image_model", "imagen-3.1") ?: "imagen-3.1",
            videoModel = prefs.getString("connector_video_model", "veo-3.1") ?: "veo-3.1",
            imageSize = prefs.getString("connector_image_size", "1024x1024") ?: "1024x1024",
            videoAspectRatio = prefs.getString("connector_video_aspect_ratio", "16:9") ?: "16:9",
            videoDuration = prefs.getInt("connector_video_duration", 5),
            responseFormat = prefs.getString("connector_response_format", "b64_json") ?: "b64_json"
        )
    }

    fun saveConfig(c: MediaConnectorConfig) {
        config = c
        activeProvider = c.provider
        prefs?.edit()?.apply {
            putString("connector_provider_id", c.provider.id)
            putString("connector_base_url", c.baseUrl)
            putString("connector_api_key", c.apiKey)
            putString("connector_image_model", c.imageModel)
            putString("connector_video_model", c.videoModel)
            putString("connector_image_size", c.imageSize)
            putString("connector_video_aspect_ratio", c.videoAspectRatio)
            putInt("connector_video_duration", c.videoDuration)
            putString("connector_response_format", c.responseFormat)
            apply()
        }
    }
}
